# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kristofer/Documents/fmeasure

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kristofer/Documents/fmeasure

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kristofer/Documents/fmeasure/CMakeFiles /home/kristofer/Documents/fmeasure/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kristofer/Documents/fmeasure/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fmeasure

# Build rule for target.
fmeasure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fmeasure
.PHONY : fmeasure

# fast build rule for target.
fmeasure/fast:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/build
.PHONY : fmeasure/fast

ACMO.o: ACMO.cpp.o

.PHONY : ACMO.o

# target to build an object file
ACMO.cpp.o:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/ACMO.cpp.o
.PHONY : ACMO.cpp.o

ACMO.i: ACMO.cpp.i

.PHONY : ACMO.i

# target to preprocess a source file
ACMO.cpp.i:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/ACMO.cpp.i
.PHONY : ACMO.cpp.i

ACMO.s: ACMO.cpp.s

.PHONY : ACMO.s

# target to generate assembly for a file
ACMO.cpp.s:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/ACMO.cpp.s
.PHONY : ACMO.cpp.s

Fmeasure.o: Fmeasure.cpp.o

.PHONY : Fmeasure.o

# target to build an object file
Fmeasure.cpp.o:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/Fmeasure.cpp.o
.PHONY : Fmeasure.cpp.o

Fmeasure.i: Fmeasure.cpp.i

.PHONY : Fmeasure.i

# target to preprocess a source file
Fmeasure.cpp.i:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/Fmeasure.cpp.i
.PHONY : Fmeasure.cpp.i

Fmeasure.s: Fmeasure.cpp.s

.PHONY : Fmeasure.s

# target to generate assembly for a file
Fmeasure.cpp.s:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/Fmeasure.cpp.s
.PHONY : Fmeasure.cpp.s

GLVA.o: GLVA.cpp.o

.PHONY : GLVA.o

# target to build an object file
GLVA.cpp.o:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/GLVA.cpp.o
.PHONY : GLVA.cpp.o

GLVA.i: GLVA.cpp.i

.PHONY : GLVA.i

# target to preprocess a source file
GLVA.cpp.i:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/GLVA.cpp.i
.PHONY : GLVA.cpp.i

GLVA.s: GLVA.cpp.s

.PHONY : GLVA.s

# target to generate assembly for a file
GLVA.cpp.s:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/GLVA.cpp.s
.PHONY : GLVA.cpp.s

GLVN.o: GLVN.cpp.o

.PHONY : GLVN.o

# target to build an object file
GLVN.cpp.o:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/GLVN.cpp.o
.PHONY : GLVN.cpp.o

GLVN.i: GLVN.cpp.i

.PHONY : GLVN.i

# target to preprocess a source file
GLVN.cpp.i:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/GLVN.cpp.i
.PHONY : GLVN.cpp.i

GLVN.s: GLVN.cpp.s

.PHONY : GLVN.s

# target to generate assembly for a file
GLVN.cpp.s:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/GLVN.cpp.s
.PHONY : GLVN.cpp.s

HISR.o: HISR.cpp.o

.PHONY : HISR.o

# target to build an object file
HISR.cpp.o:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/HISR.cpp.o
.PHONY : HISR.cpp.o

HISR.i: HISR.cpp.i

.PHONY : HISR.i

# target to preprocess a source file
HISR.cpp.i:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/HISR.cpp.i
.PHONY : HISR.cpp.i

HISR.s: HISR.cpp.s

.PHONY : HISR.s

# target to generate assembly for a file
HISR.cpp.s:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/HISR.cpp.s
.PHONY : HISR.cpp.s

TENG.o: TENG.cpp.o

.PHONY : TENG.o

# target to build an object file
TENG.cpp.o:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/TENG.cpp.o
.PHONY : TENG.cpp.o

TENG.i: TENG.cpp.i

.PHONY : TENG.i

# target to preprocess a source file
TENG.cpp.i:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/TENG.cpp.i
.PHONY : TENG.cpp.i

TENG.s: TENG.cpp.s

.PHONY : TENG.s

# target to generate assembly for a file
TENG.cpp.s:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/TENG.cpp.s
.PHONY : TENG.cpp.s

TENV.o: TENV.cpp.o

.PHONY : TENV.o

# target to build an object file
TENV.cpp.o:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/TENV.cpp.o
.PHONY : TENV.cpp.o

TENV.i: TENV.cpp.i

.PHONY : TENV.i

# target to preprocess a source file
TENV.cpp.i:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/TENV.cpp.i
.PHONY : TENV.cpp.i

TENV.s: TENV.cpp.s

.PHONY : TENV.s

# target to generate assembly for a file
TENV.cpp.s:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/TENV.cpp.s
.PHONY : TENV.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/fmeasure.dir/build.make CMakeFiles/fmeasure.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... fmeasure"
	@echo "... edit_cache"
	@echo "... ACMO.o"
	@echo "... ACMO.i"
	@echo "... ACMO.s"
	@echo "... Fmeasure.o"
	@echo "... Fmeasure.i"
	@echo "... Fmeasure.s"
	@echo "... GLVA.o"
	@echo "... GLVA.i"
	@echo "... GLVA.s"
	@echo "... GLVN.o"
	@echo "... GLVN.i"
	@echo "... GLVN.s"
	@echo "... HISR.o"
	@echo "... HISR.i"
	@echo "... HISR.s"
	@echo "... TENG.o"
	@echo "... TENG.i"
	@echo "... TENG.s"
	@echo "... TENV.o"
	@echo "... TENV.i"
	@echo "... TENV.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

